ifndef root_dir
	root_dir:=..
endif

INCS+=-I../src_module1/include -I../src_module2/include -I../lib_module1/include -I../lib_module2/include -I../so_module1/include -I../so_module2/include

include $(root_dir)/makefile_src
